### ISSUE TITLE
[FEATURE] Add linter for golang code in CI

### ISSUE THREAD

**Issue by yunwei37** [linuxkerneltravel/lmp#394]
**Is your feature request related to a problem? Please describe.**

Use some linter to improve the quality of golang code, and reduce the code review time. We have a lot of golang code now.

**Describe the solution you'd like**

Use https://github.com/golangci/golangci-lint in CI of LMP project, and fix the problem find by the linter.

**Provide usage examples**

See: https://github.com/cloudflare/ebpf_exporter/blob/7dbbd85f74318e0da49ea54c8aeaa9bc7c71aad8/.github/workflows/ci.yml#L98

An example golangci-lint linter for ebpf_exporter:
```
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.0
        env:
          CGO_LDFLAGS: "-l bpf"
```
